/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hoang Quyet
 */
import java.awt.BasicStroke;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import javax.swing.JPanel;

/**
 *
 * @author trand
 */
public class cua extends JPanel{

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
public void paint(Graphics g){
    Graphics2D g2d = (Graphics2D) g;
        g2d.setStroke(new BasicStroke(3));
        int width = getRootPane().getWidth();
        int height = getRootPane().getHeight();
        int middle = width / 2;
        Rectangle name = new Rectangle(middle - 150, height / 6, 300, 100);
        g2d.draw(name);
        g2d.setFont(new Font("Segue UI", Font.BOLD, 30));
        g2d.drawString("PHÒNG 305", name.x + 60, name.y + 60);
}
}

